dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    #map @chainlink to the repository name
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
wallets:
  from_key: ${PRIVATE_KEY}

# Remember to put this in! It's going to load the .env file.
dotenv: .env
networks:
  # set defaut network to run on.
  # default: ganache-local-test
  rinkeby:
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    verify: True
  mainnet-fork:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
  development:
    verify: False
  ganache-local-test:
    verify: False

