/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20 } from "./IERC20";
export type { ILendingPool } from "./ILendingPool";
export type { IWeth } from "./IWeth";
